- name: Create Nginx config directory
  file:
    path: /opt/containers/nginx
    state: directory

- name: Copy Nginx config
  copy:
    src: nginx.conf
    dest: /opt/containers/nginx/nginx.conf
    mode: "0644"

- name: Run Nginx container
  docker_container:
    name: nginx-reverse-proxy
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /opt/containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    etc_hosts:
      homelab.local: "127.0.0.1"

- name: Add homelab.local to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 homelab.local"
    state: present
