---
- name: Create 13ft directory
  file:
    path: /opt/containers/13ft
    state: directory
    mode: "0755"

- name: Deploy 13ft container
  copy:
    dest: /opt/containers/13ft/13ft-compose.yml
    content: |
      services:
        13ft:
          image: ghcr.io/wasi-master/13ft:latest 
          container_name: 13ft
          restart: unless-stopped
          ports:
            - "5000:5000"

- name: Launch 13ft
  shell: docker-compose -f 13ft-compose.yml up -d
  args:
    chdir: /opt/containers/13ft
