---
- name: Create paperless directory
  file:
    path: /opt/containers/paperless
    state: directory
    mode: "0755"

- name: Deploy paperless container
  copy:
    dest: /opt/containers/paperless/paperless-compose.yml
    content: |
      services:
        broker:
          image: docker.io/library/redis:7
          restart: unless-stopped
          volumes:
            - redisdata:/data

        webserver:
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          restart: unless-stopped
          depends_on:
            - broker
          ports:
            - "8000:8000"
          volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            - ./export:/usr/src/paperless/export
            - ./consume:/usr/src/paperless/consume
          env_file: docker-compose.env
          environment:
            PAPERLESS_REDIS: redis://broker:6379
      volumes:
        data:
        media:
        redisdata:

- name: Create docker-compose.env
  copy: 
    dest: /opt/containers/paperless/docker-compose.env
    content: |
      #USERMAP_UID=1000

- name: Launch paperless
  shell: docker-compose -f paperless-compose.yml up -d
  args:
    chdir: /opt/containers/paperless
