---
- name: Create jellyfin directory
  file:
    path: /opt/containers/jellyfin
    state: directory
    mode: "0755"

- name: Deploy jellyfin container
  copy:
    dest: /opt/containers/jellyfin/jellyfin-compose.yml
    content: |
      services:
        jellyfin:
          image: lscr.io/linuxserver/jellyfin
          container_name: jellyfin
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
          restart: unless-stopped
          ports:
            - "8096:8096"
          volumes:
            - /opt/containers/jellyfin:/config
            - /media/tvshows:/data/tvshows

- name: Launch jellyfin
  shell: docker-compose -f jellyfin-compose.yml up -d
  args:
    chdir: /opt/containers/jellyfin
