- hosts: homelab
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: jellyfin, tags: jellyfin }
    - { role: pihole, tags: pihole }
    - { role: glance, tags: glance }
    - { role: nginx, tags: nginx }
    - { role: 13ft, tags: 13ft }
