- hosts: homelab
  become: yes
  roles:
    - { role: docker, tags: docker }
    - { role: jellyfin, tags: jellyfin }
    - { role: pihole, tags: pihole }
    - { role: traefik, tags: traefik }
    - { role: changedetection, tags: changedetection }
    - { role: paperless, tags: paperless }
