- name: Enable NFS
  ansible.posix.firewalld:
    service: nfs
    state: enabled
    permanent: true
    immediate: true
    offline: true

- name: Enable VNC
  ansible.posix.firewalld:
    service: vnc
    state: enabled
    permanent: true
    immediate: true
    offline: true
