---
- name: Create changedetection directory
  file:
    path: /opt/containers/changedetection
    state: directory
    mode: "0755"

- name: Deploy changedetection
  copy:
    dest: /opt/containers/changedetection/changedetection-compose.yml
    content: |
      services:
        changedetection:
          image: lscr.io/linuxserver/changedetection.io:latest
          container_name: changedetection
          environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - BASE_URL= #optional
            - PLAYWRIGHT_DRIVER_URL= #optional
          volumes:
            - /path/to/changedetection/config:/config
          ports:
            - 5010:5000
          restart: unless-stopped

- name: Launch changedetection
  shell: docker-compose -f changedetection-compose.yml up -d
  args:
    chdir: /opt/containers/changedetection
