- name: Install Docker
  dnf:
    name:
      - docker
      - docker-compose
    state: present
    update_cache: yes

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started
